### ISSUE TITLE
How To Install a Agent?

### ISSUE THREAD

**Issue by MZC-CSC** [cloud-barista/api#7]
Swagger에서 Agent 설치여부를 확인하는 API는 있으나 Agent설치에 대한 API가 보이지 않습니다.
혹시 Check해서 없으면 설치를 하나요?

[/honeybee/source_group/{sgId}/agent_check](https://cloud-barista.github.io/api/?url=https://raw.githubusercontent.com/cloud-barista/cm-honeybee/main/server/pkg/api/rest/docs/swagger.yaml#/[On-premise]%20SourceGroup/get_honeybee_source_group__sgId__agent_check)
Check Agent SourceGroup

Check Agent in source group. Show each status by returning agent info list.

**Comment by seokho-son** [comment]
@MZC-CSC honeybee 쪽으로 질문 부탁드립니다. :)
